version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $(echo $SHARED_ECR_REPOSITORY_URL | cut -d/ -f1)

  build:
    commands:
      - echo "Build started on $(date)"
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:-latest}
      
      - echo "Building Docker image..."

      - docker build -t $SHARED_ECR_REPOSITORY_URL:$IMAGE_TAG .

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Pushing Docker image to ECR..."
      - docker push $SHARED_ECR_REPOSITORY_URL:$IMAGE_TAG
      - echo "Push complete."
      - echo "Writing image tag $IMAGE_TAG to SSM Parameter Store..."
      - aws ssm put-parameter --name "$SSM_PARAMETER_NAME" --value $IMAGE_TAG --type "String" --overwrite
      - echo "SSM Parameter updated."

      - echo "Triggering Spacelift ECS deployment stack..."
      - export SPACELIFT_CREDS=$(aws secretsmanager get-secret-value --secret-id $SPACELIFT_API_SECRET_ARN --query SecretString --output text)
      - export SPACELIFT_KEY_ID=$(echo $SPACELIFT_CREDS | jq -r .SPACELIFT_API_KEY_ID)
      - export SPACELIFT_KEY_SECRET=$(echo $SPACELIFT_CREDS | jq -r .SPACELIFT_API_KEY_SECRET)
      
      - |
        curl -s \
          -X POST \
          -H "Authorization: Bearer $SPACELIFT_KEY_ID/$SPACELIFT_KEY_SECRET" \
          -H "Content-Type: application/json" \
          --data '{
            "query": "mutation TriggerRun($stackId: ID!) { runTrigger(stackId: $stackId) { id } }",
            "variables": {
              "stackId": "'"$SPACELIFT_ECS_STACK_ID"'"
            }
          }' \
          'https://leon-test.app.spacelift.io' # ！！！请替换成您的 Spacelift 域名
      - echo "Spacelift ECS stack triggered."