version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $(echo $SHARED_ECR_REPOSITORY_URL | cut -d/ -f1)

  build:
    commands:
      - echo "Build started on $(date)"
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:-latest}
      - echo "Building Docker image..."
      - docker build -t $SHARED_ECR_REPOSITORY_URL:$IMAGE_TAG .

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Pushing Docker image to ECR..."
      - docker push $SHARED_ECR_REPOSITORY_URL:$IMAGE_TAG
      - echo "Push complete."
      - echo "Writing image tag to SSM..."
      - aws ssm put-parameter --name "$SSM_PARAMETER_NAME" --value $IMAGE_TAG --type "String" --overwrite
      - echo "SSM updated."
      - echo "Getting Spacelift credentials..."
      - export SPACELIFT_CREDS=$(aws secretsmanager get-secret-value --secret-id $SPACELIFT_API_SECRET_ARN --query SecretString --output text)
      - export SPACELIFT_KEY_ID=$(echo $SPACELIFT_CREDS | jq -r .SPACELIFT_API_KEY_ID)
      - export SPACELIFT_KEY_SECRET=$(echo $SPACELIFT_CREDS | jq -r .SPACELIFT_API_KEY_SECRET)
      - echo "Getting JWT token..."
      - SPACELIFT_JWT_RESPONSE=$(curl -s -X POST -H "Content-Type:application/json" --data '{"query":"mutation($id:ID!,$secret:String!){apiKeyUser(id:$id,secret:$secret){jwt}}","variables":{"id":"'"$SPACELIFT_KEY_ID"'","secret":"'"$SPACELIFT_KEY_SECRET"'"}}' "https://leon-test.app.spacelift.io/graphql")
      - echo "Response - $SPACELIFT_JWT_RESPONSE"
      - export SPACELIFT_JWT=$(echo $SPACELIFT_JWT_RESPONSE | jq -r .data.apiKeyUser.jwt)
      - test "$SPACELIFT_JWT" != "null" && test -n "$SPACELIFT_JWT" || (echo "JWT failed" && exit 1)
      - echo "Triggering stack..."
      - TRIGGER_RESPONSE=$(curl -s -X POST -H "Authorization:Bearer $SPACELIFT_JWT" -H "Content-Type:application/json" --data '{"query":"mutation($stackId:ID!){runTrigger(stack:$stackId){id}}","variables":{"stackId":"ec-demo-dev"}}' "https://leon-test.app.spacelift.io/graphql")
      - echo "Response - $TRIGGER_RESPONSE"
      - RUN_ID=$(echo $TRIGGER_RESPONSE | jq -r .data.runTrigger.id)
      - test "$RUN_ID" != "null" && test -n "$RUN_ID" || (echo "Trigger failed" && exit 1)
      - echo "Success! Run ID - $RUN_ID"